- hosts: host
  become: yes
  vars:
    - packages: ["git", "nmap"]
    - user: "admin"
    - repo_name: "name"
    - repo_url: "http://dummy.repo.com"
  tasks:
  - name: Check for GitHub Project Directory
    shell: '[ -d "/var/github" ] && echo "Directory /var/github exists." || mkdir /var/github && echo "Directory /var/github is now created."'

  - name: Check for Project Directory
    shell: '[ -d "/var/github/{{repo_name}}" ] && echo "Directory /var/github/{{repo_name}} exists." || git clone {{repo_url}}:/var/github'

  - name: Pull Project
    shell: '[ -d "/var/github/${{repo_name}}" ] && cd /var/github/${{repo_name}} && git pull origin master | echo "Pulling Repoitory" && echo "Done Pulling" || echo "Directory does not exist"'

  - name: Deploy Kubernetes Service
    shell: cd /var/github/${{repo_name}} && kubectl apply -f deploy.yaml