apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: ro-authenitication-service
spec:
  type: NodePort
  selector:
    app: ro-authenitication-service
  ports:
    - port: 8088 # The port that the service is running on in the cluster
      protocol: TCP
      nodePort: 31516

---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ro-authenitication-service
spec:
  selector:
    matchLabels:
      app: ro-authenitication-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ro-authenitication-service
    spec:
      containers:
        - name: ro-authenitication-service
          image: registry.developer.co.zw/developer/ro-authenitication-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088 # The port that the container is running on in the cluster
          envFrom:
          - configMapRef:
              name: ro-booking-service-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ro-booking-service-config
data:
  MONGOURI: mongodb+srv://retrospecs:XLteY3GscHnLyFvU@cluster0.3uaovad.mongodb.net/?retryWrites=true&w=majority
