FROM openjdk:11
ARG PRIVATE_KEY=t7uuuGJCeWH2LFcmDKTgpt3Y4faebukr
ARG TOKEN_LIFE=86400000
ARG PG_DB_USER=postgres
ARG PG_DB_PASSWORD=qub3dl@b123*
ENV PG_DB_USER=${PG_DB_USER}
ENV PG_DB_PASSWORD=${PG_DB_PASSWORD}
ENV TOKEN_LIFE=${TOKEN_LIFE}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=production","/app.jar"]